:imagesdir: doc/images

= Waste Commons Scotland

This repository contains the source code and build instructions for
the *Waste Commons Scotland* web application (*WCS*).

The development of WCS is one of the outcomes
of the https://www.stir.ac.uk/research/hub/contract/933675[Data Commons Scotland]
research project.

The objectives for WCS include:

* Help its user community find, understand and comment on
the _open data_ about *waste* management in Scotland.
* Be a demonstrator of the findings from the encompassing research project,
and be an archetype for future portals onto other categories of _open data_.

WARNING: The project is at an early stage and this is mostly _placeholder_ content.

---

include::doc/scenario.adoc[]

== Building and running

WCS is built on https://github.com/fulcrologic/fulcro[Fulcro] rapid-application-development framework and its many underlying technologies.

=== Setting up the environment, tools, etc.

* Read http://book.fulcrologic.com/#_install_supporting_tools
* Google Chrome (say, version 83.0.4103.116)
** Open the developer tools console: `Cmd Option J`.
** Then customise as per http://book.fulcrologic.com/#_configure_chrome_development_setting +
also add the Fulcro Inspect extension.
* JDK 11.0.5
* Clojure 1.10.1
* npm 5.5.0
* node 8.9.1
* shadow-cljs 2.10.17
* IntelliJ IDEA (say, version Community 2020.1) +
with the Cursive plugin installed.
** `Import Project` -> choose the `deps.edn` file.

=== For an interactive development session

==== In terminal A...

Start a REPL for running the backend...
[source, bash]
-----
clj -A:dev:datomic
-----

Within the resulting REPL, start the backend...
[source, clojure]
-----
(clojure.core/require 'development)
(development/go)
-----

Useful within this REPL...
[source, clojure]
-----
(require '[datomic.api :as d])
(require '[wcs.components.datomic :refer [datomic-connections]])
(def db (d/db (:main datomic-connections)))

(def ash (d/pull db '[*] [:account/email "ash@waste-commons.scot"])) ; where :account/email uniquely identifies the entity
(pprint ash)

(d/q '[:find [?v ...] :where [?e :category/label ?v]] db)
(d/q '[:find [?v ...] :where [?e :account/name ?v]] db)
-----

==== In terminal B...

Start a REPL for transpiling the frontend...
[source, bash]
-----
npx shadow-cljs watch main
-----

==== Using Google Chrome...

* shadow-cljs server: http://localhost:9630/
* test outcomes: http://localhost:8081/
* web ui: http://localhost:3000/

==== Using Intellij IDEA...

Create a REPL configuration...
`Run/Debug Configurations' -> `Templates` -> `Clojure REPL` -> `remote` +
With the values: `nREPL` `localhost` `9000`

Run that configuration to connect to the nREPL in Google Chrome +
and select `cljs` from the dropdown...
[source, clojure]
-----
(shadow/repl :main)
(js/alert "Testing!")
-----

=== For deployment

* Generate a POM file...
[source, bash]
-----
clojure -Spom
-----
* Build the frontend...
[source, bash]
----
npx shadow-cljs release main
----
* Build the backend...
[source, bash]
----
clojure -A:depstar:dev:datomic -m hf.depstar.uberjar wcs.jar -C -m wcs.core  -v
----
* Run the backend...
[source]
----
export PORT=8085
java -jar wcs.jar
----

