= Waste Commons Scotland

One of the objectives of the http://stir.ac.uk/dcs/TODO[Data Commons Scotland] project
is to develop a prototype web application that helps its user community
find, understand and comment on the _open data_ about waste management in Scotland.
The resulting web application is called *Waste Commons Scotland* (*WCS*),
and this repository contains its source code and build instructions.

WARNING: This is _a work-in-progress_.

== Building and running

=== Setting up the environment, tools, etc.

* Read http://book.fulcrologic.com/#_install_supporting_tools
* Google Chrome (say, version 83.0.4103.116)
** Open the developer tools console: `Cmd Option J`.
** Then customise as per http://book.fulcrologic.com/#_configure_chrome_development_setting +
also add the Fulcro Inspect extension.
* JDK 11.0.5
* Clojure 1.10.1
* npm 5.5.0
* node 8.9.1
* shadow-cljs 2.10.17
* IntelliJ IDEA (say, version Community 2020.1) +
with the Cursive plugin installed.
** `Import Project` -> choose the `deps.edn` file.

=== For an interactive development session

==== In terminal A...

[source, bash]
-----
clj -A:dev:datomic
-----

Within the resulting REPL (for running the backend), start the backend...
[source, clojure]
-----
(clojure.core/require 'development)
(development/go)
-----

Useful within this REPL...
[source, clojure]
-----
(require '[datomic.api :as d])
(require '[com.example.components.datomic :refer [datomic-connections]])
(def db (d/db (:main datomic-connections)))

(def ash (d/pull db '[*] [:account/email "ash@mac.com"])) ; where :account/email uniquely identifies the entity
(pprint ash)

d/q '[:find [?v ...] :where [?e :category/label ?v]] db)
(d/q '[:find [?v ...] :where [?e :account/name ?v]] db)
-----

==== In terminal B...

[source, bash]
-----
npx shadow-cljs -A:f3-dev:rad-dev watch main
-----

Within the resulting REPL (for transpiling the fontend), connect to the nREPL in the browser at localhost:9000
[source, clojure]
-----
(shadow/repl :main)
(js/alert "Testing!")
-----

==== Using Google Chrome...

* shadow-cljs server: http://localhost:9630/
* test outcomes: http://localhost:8081/
* web ui: http://localhost:3000/

== For deployment

* Edit `dep.edn` and `shadow-cljs.edn` as per https://github.com/seancorfield/depstar
 and https://folcon.github.io/post/2020-04-12-Fulcro-on-Heroku/
* Create a `com.example.core/-main`
* Generate a POM file:
[source, bash]
-----
clojure -Spom
-----
* Build the frontend:
[source, bash]
----
npx shadow-cljs release main
----
* Build the backend:
[source, bash]
----
clojure -A:depstar:dev:datomic -m hf.depstar.uberjar wcs.jar -C -m com.example.core  -v
----
* Run the backend:
[source]
----
java -jar wcs.jar
----

